name: Build Windows with xmake

on:
  push:
    branches:
      - master
  pull_request: 

jobs:
  build:
    runs-on: windows-latest 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build with xmake
        run: |
          Set-ExecutionPolicy RemoteSigned -Scope CurrentUser -Force
          irm get.scoop.sh | iex
          scoop install xmake
          xmake f -m release
          xmake  

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-binary
          path: build/release/windows/x64/moonit.exe
